### ISSUE TITLE
What should be transferred as file?

### ISSUE THREAD

**Issue by matveychuk** [Fausto95/react-s3#2]
Please advise what should be transferred as file for command  ReactS3.upload(file, config). Some object or pathname?

**Comment by Fausto95** [comment]
Hi!
File is actually an object that looks like this:
<img width="1259" alt="capture d ecran 2018-02-20 a 21 02 29" src="https://user-images.githubusercontent.com/23306911/36446452-8e02ff70-1681-11e8-8f3b-503f1f856c7d.png">

**Comment by matveychuk** [comment]
Thx. You really helped me.

**Comment by vishnujnv15** [comment]
The image really helps.
I was trying file-path, custom object and what not.
