### ISSUE TITLE
Don't work in root directory

### ISSUE THREAD

**Issue by AlexeyShalik** [Fausto95/react-s3#3]
If i want save my image in root s3. I can't save they there.

**Comment by Fausto95** [comment]
In which case do you want to save your image in the S3's root directory ?

**Comment by AlexeyShalik** [comment]
I want save my image in the S3's root directory, because I use AWS lambda for image resize. AWS Lambda work only root directory.

**Comment by Fausto95** [comment]
Just fixed the issue! 
Now you can save your file to the S3's root directory. 
Give a look in the ReadMe and make sure to upload this lib to the #v1.2.4
