### ISSUE TITLE
Could not install 

### ISSUE THREAD

**Issue by sathikanna** [Fausto95/react-s3#4]
Hi, i could not istall in my new project ..
getting following error 
npm install --save react-s3
npm WARN react-trend@1.2.4 requires a peer of react@ but none is installed. You must install peer dependencies yourself.

npm ERR! path G:\haachy\haachynew\node_modules\.bin\webpack
npm ERR! code EEXIST
npm ERR! Refusing to delete G:\haachy\haachynew\node_modules\.bin\webpack: is outside G:\haachy\haachynew\node_modules\webpack and not a link
npm ERR! File exists: G:\haachy\haachynew\node_modules\.bin\webpack
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MY PC\AppData\Roaming\npm-cache\_logs\2018-03-05T14_30_02_283Z-debug.log

**Comment by Fausto95** [comment]
Installing react should fix the error
